### ISSUE TITLE
Request to add monitoring for Keycloak

### ISSUE THREAD

**Issue by gireeshdeepakr** [vexxhost/atmosphere#1010]
Hi Team,

As we have started using Keycloak in our Production Openstack cloud. We are looking for detailed monitoring on Keycloak to ensure its optimal performance, security, and reliability. Please consider below requirements, additionally, if you think any additional metrics to add, please do.

1. CPU usage 
2. Heap usage and garbage collection
3. Thread Count
4. Number of incoming HTTP requests to Keycloak.
5. Successful logins count
6. Failed Logins count
8. Latency (Time takes for successful auth and authorization)
9. Throughput (successful login attempts per second)
10. Number of token requests made to Azure AD.
11. Rate at which access tokens are issued.
12. Token lifetime / expiration
13. Token revocations.
14. Active sessions, session timeouts, and session invalidation
15. Cache hits, misses, and eviction rates
16. Any other potential metrics that can give us health of the app/service?

Resources for more info: 
https://www.keycloak.org/server/configuration-metrics
https://www.keycloak.org/keycloak-benchmark/kubernetes-guide/latest/util/prometheus

**Comment by okozachenko1203** [comment]
Atmosphere is using bitnami helm chart to deploy keycloak so you can enable collecting metrics by configuring keycloak helm chart values. https://github.com/bitnami/charts/tree/main/bitnami/keycloak#metrics-parameters
You can add the following vars to the inventory.
```yaml
keycloak_helm_values:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
```

**Comment by gireeshdeepakr** [comment]
The Bitnami Helm chart does not export the /metrics endpoint by default. We had to edit the StatefulSet to add it. After that, we were able to create a service monitor and able to export "System and JVM" metrics. But missing below

- keycloak_login_attempts
- keycloak_logins_total
- keycloak_failed_client_login_attempts
- keycloak_refresh_tokens
- keycloak_refresh_tokens_errors
- keycloak_registrations
- keycloak_registrations_errors
- keycloak_code_to_tokens
- keycloak_code_to_tokens_errors
- keycloak_request_duration

Also, official doc https://www.keycloak.org/server/configuration-metrics#_querying_metrics didn't mention about these metrics. Need advice on this. 
Thanks
