### ISSUE TITLE
upgrade openstackclient version

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/atmosphere#1014]
The current version is 5.8.0. With this version, we face this issue https://storyboard.openstack.org/#!/story/2009287
Need to upgrade it to 6.x or 5.6.x>5.6.0.
As a workaround, you can add `--os-volume-api-version 3.1`.
```sh
openstack image create --volume volumeId --os-volume-api-version 3.1 imageName
```

**Comment by mnaser** [comment]
I think @fitbeard had a really cool solution, if they don't have time to pursue it, we can finish it up and use a containerized CLI

**Comment by mnaser** [comment]
Since we have containerized CLI, this is solved :)
