### ISSUE TITLE
Atmosphere Operator: optional deployment of ingress-nginx

### ISSUE THREAD

**Issue by runlevel-six** [vexxhost/atmosphere#105]
Our deployment of Atmosphere includes a slightly different architecture for Kubernetes, including a custom deployment of ingress-nginx, and one that uses metal-loadbalancer instead of keepalived. Prior to the move of ingress-nginx into the Atmosphere operator this was simple enough to manage, as we just commented out the deployment of keepalived and ingress-nginx in the openstack Ansible playbook. 

Per the conversation we had last Friday (September 30), it would be ideal if instead of maintaining a fork of the atmosphere operator with the flows.py code commented out for the deployment of ingress-nginx, if instead this could be managed much like memcached (with a simple config override `config.memcached.enabled`) then the operator would be a more flexible option for us.

**Comment by mnaser** [comment]
@runlevel-six can you checkout if that PR does initially what you're looking for?  you can feel free to test that branch while we wait for it to pass tests.

**Comment by mnaser** [comment]
I think the issue here is that this image is not the up to date/fixed one:

```
atmosphere_image: quay.io/vexxhost/atmosphere:0.4.1 # x-release-please-version
```

You'll have to build the image and upload it manually somewhere, or use `tty.sh` similar to how we use it in Molecule and point to it.  However, I'll cut the release shortly anyhow that includes this.

**Comment by mnaser** [comment]
@runlevel-six just cut 0.5.0 off, so you should be able to point the collection to that and get the fixes in :)

FYI, you could totally use the overrides and have Atmosphere manage the ingress component for you, just with your own overrides, if that works for you.

**Comment by runlevel-six** [comment]
@mnaser this worked well for us. Thank you!

And you are right - this is something we are discussing. The customization on our end is mainly security focused, which would be easily adopted into the overrides available in Atmosphere. The only other change we make is running ingress-nginx in its own namespace which is not a Helm variable, if I remember right.
