### ISSUE TITLE
Introduce major releases

### ISSUE THREAD

**Issue by mnaser** [vexxhost/atmosphere#1068]
At the moment, `main` simply points to a single version of OpenStack.  However, we've noticed that customers do sometimes want to run things for longer.  It also makes it tougher for upgrade paths, therefore, we're going to plan to adding major releases that correspond to OpenStack releases, with the plan being the following:

- [x] `main`: move all images to point to `master` branches of OpenStack
- [x] `stable/zed`: branch from `main`, update all images to point to `stable/zed` (https://github.com/vexxhost/atmosphere/pull/1069)
- [x] `stable/zed`: release as `1.x`
- [x] `stable/2023.1`: branch from `main`, update all images to point to `stable/2023.1` (https://github.com/vexxhost/atmosphere/pull/1227)
- [x] `stable/2023.1`: introduce job to deploy `stable/zed` and upgrade to `stable/2023.1` (https://github.com/vexxhost/atmosphere/issues/1282)
- [x] `stable/2023.1`: release as `2.x`
- [x] `stable/2023.2`: branch from `main`, update all images to point to `stable/2023.2`
- [x] `stable/2023.2`: introduce jobs to deploy from `stable/2023.1` and upgrade to `stable/2023.2`
- [x] `stable/2023.2`: release as `3.x`
- [x] `stable/2024.1`: branch from `main`, update all images to point to `stable/2024.1`
- [x] `stable/2024.1`: introduce jobs to deploy from `stable/2023.2` and upgrade to `stable/2024.1`
- [x] `stable/2024.1`: release as `4.x`
- [x] https://github.com/vexxhost/atmosphere/issues/1267

For upstream, we'll support releases on a best effort basis and deal with direct customers on individual basis if they are really behind.  It'll allow users to spend more time on their releases.

For upgrades, the ideal path would be major => major without jumping, and for those who feel comfortable can jump releases.

**Comment by mpiscaer** [comment]
This sounds very help full and good.

**Comment by mnaser** [comment]
Alright, the next step here is to update `main` to point at `master` OpenStack, since we've released 1.11.0 for those users who want to continue to carry on using Zed.

From there, we'll branch out the other releases.

**Comment by mnaser** [comment]
The PR https://github.com/vexxhost/atmosphere/pull/1090 brings the `main` branch in line with what we're doing in `stable/zed` so that backports can happen cleaner over there.

**Comment by okozachenko1203** [comment]
just for note: ovn upgrade https://github.com/vexxhost/atmosphere/issues/1194

**Comment by mnaser** [comment]
We just need to fix the [2023.1 to 2023.2](https://ci.atmosphere.dev/t/atmosphere/builds?job_name=atmosphere-molecule-aio-upgrade-2023.2-openvswitch&skip=0) upgrade jobs and release the new series and we're good to go. :)

**Comment by mnaser** [comment]
This is finally done!
