### ISSUE TITLE
Push all service logs to OpenSearch

### ISSUE THREAD

**Issue by Meritadev** [vexxhost/atmosphere#11]
At the moment, once a pod dies, the logs are gone forever and they cannot be recovered anymore.  This is not good in the long term since it makes it very hard to troubleshoot things

We need to push logs into the ElasticSearch that we run.  I think the best way to do this is to start making sure that all systems push JSON logs, and then maybe run a fluent-bit side car that pushes all those JSON logs to the OpenSearch cluster

**Comment by mnaser** [comment]
we're already pushing all logs to vector.
