### ISSUE TITLE
Implement rados gateway

### ISSUE THREAD

**Issue by guilhermesteinmuller** [vexxhost/atmosphere#111]

**Comment by mnaser** [comment]
@guilhermesteinmuller I think what we're going to aim to do for this initially (to reduce the amount of work) is to start off by perhaps integrating the Rook operator and integrating it with an external cluster (the one we deploy).

With that in place, we're able to let Rook create pools and RGW instances on the existing cluster and avoid having to write all that managed code.

If you want to start by kicking things off, you'll have to create by adding a task for adding a HelmRepository and HelmRelease for Ceph in a PR:

https://rook.io/docs/rook/v1.9/helm-operator.html

In here:

https://github.com/vexxhost/atmosphere/blob/main/atmosphere/flows.py

Once you have that initial part in place, you should be able to test it out by running the following:

```
poetry run pytest atmosphere/tests/integration
```

and see if that runs successfully, if it does, you can also try a `molecule converge` and see if the Rook operator successfully goes up.

Once you have that PR up, we'll be able to iterate into the next step of 'integrating' the external Ceph cluster into it.

**Comment by guilhermesteinmuller** [comment]
i kicked off a draft here https://github.com/vexxhost/atmosphere/pull/131 but this is still wip

**Comment by mnaser** [comment]
we're testing this in https://github.com/vexxhost/atmosphere/pull/323 and we'll land that sometime tomorrow and rgw will be enabled out of the box!
