### ISSUE TITLE
download.cirros-cloud.net

### ISSUE THREAD

**Issue by mpiscaer** [vexxhost/atmosphere#124]
Can it be that download.cirros-cloud.net has a rate limit?

I got the following error:

failed: [ctl1] (item={'name': 'cirros', 'source_url': 'http://download.cirros-cloud.net/0.5.1/', 'image_file': 'cirros-0.5.1-x86_64-disk.img', 'min_disk': 1, 'disk_format': 'qcow2', 'container_format': 'bare', 'is_public': True}) => {"ansible_loop_var": "item", "changed": false, "dest": "/tmp/cirros-0.5.1-x86_64-disk.img", "elapsed": 5, "gid": 0, "group": "root", "item": {"container_format": "bare", "disk_format": "qcow2", "image_file": "cirros-0.5.1-x86_64-disk.img", "is_public": true, "min_disk": 1, "name": "cirros", "source_url": "http://download.cirros-cloud.net/0.5.1/"}, "mode": "0600", "msg": "Request failed", "owner": "root", "response": "HTTP Error 503: Egress is over the account limit.", "size": 16338944, "state": "file", "status_code": 503, "uid": 0, "url": "http://download.cirros-cloud.net/0.5.1/cirros-0.5.1-x86_64-disk.img"}

**Comment by mnaser** [comment]
It looks like it's currently hosted at DreamHost, I think they may have hit their bandwidth limit but it looks like it's working again now.

is this a transient issue or always happening?  I think the only way around this is to setup our own private mirror to avoid those CI failures.

**Comment by mpiscaer** [comment]
Till now it was a one timer.

**Comment by runlevel-six** [comment]
I have had this happen a few times as well. After it happened a few times I manually downloaded the image and just upload it myself to Glance after the Openstack playbook completed (thus I leave the `openstack_helm_glance_images` Ansible variable empty instead of having it go get this image direct).

**Comment by mnaser** [comment]
we're moving this into our block storage to avoid this issue.

**Comment by mnaser** [comment]
closed by https://github.com/vexxhost/atmosphere/pull/158

**Comment by guilhermesteinmuller** [comment]
hey guys, so I'm closing this based on https://github.com/vexxhost/atmosphere/commit/2edc65ce0cdb8e4de4432729d3762afbb812cd0c so we won't get any retry limits so far since it's hosted in Vexxhost's object storage.
