### ISSUE TITLE
Integrate migration service

### ISSUE THREAD

**Issue by mnaser** [vexxhost/atmosphere#1242]
There is a big need for a migration service and it seems that we've got an existing powerful project in place that we can take advantage of:

- https://github.com/cloudbase/coriolis
- https://github.com/cloudbase/coriolis-web
- https://github.com/cloudbase/coriolis-snapshot-agent

Client:
- https://github.com/cloudbase/python-coriolisclient

Extras:
- https://github.com/cloudbase/coriolis-openstack-utils
- https://github.com/cloudbase/coriolis-resources

We can easily integrate this and add the dashboard to be powered by Keystone SSO

**Comment by fnpanic** [comment]
Will this be added to atmosphere soon?

**Comment by mnaser** [comment]
@fnpanic Coriolis is an open core product so we are unable to bring it in, we've built Migratekit instead:

https://github.com/vexxhost/migratekit
