### ISSUE TITLE
bug: allow ssh login for nova user for nova-compute-ssh image

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/atmosphere#1245]
## Context
Instance migraiton is failing with `protocol error: mtime.sec not present` error.

## Reason
We use `/usr/sbin/nologin` for users created during image to not allow ssh login.
https://github.com/vexxhost/atmosphere/blob/abb177586fda668aea747e54231d5d1630bfb57e/images/openstack-runtime/Dockerfile#L20C13-L23

it should be allowed for nova-compute-ssh.

**Comment by mnaser** [comment]
Good catch.  Hopefully this doesn't bite us again, would be nice if there was some 'unit tests' for images that exist, but oh well :)
