### ISSUE TITLE
rook ceph exporter init failed with secret "rook-ceph-exporter-keyring" not found

### ISSUE THREAD

**Issue by ricolin** [vexxhost/atmosphere#1302]
```
root@instance:/home/ubuntu# kubectl -n openstack describe pod rook-ceph-exporter-instance-54df8dfc9b-2v996
Events:
  Type     Reason       Age                  From     Message
  ----     ------       ----                 ----     -------
  Warning  FailedMount  42s (x869 over 29h)  kubelet  MountVolume.SetUp failed for volume "rook-ceph-exporter-keyring" : secret "rook-ceph-exporter-keyring" not found
```

This is due to missing secret like reported on https://github.com/rook/rook/issues/14275
This issue affect rook-ceph > 1.13.0 as https://github.com/rook/rook/pull/13239 introduced separate keyring for exporter but somehow didn't actually create exporter keyrings out

**Comment by parth-gr** [comment]
Seems like you havent create the external cephcluster CR https://github.com/rook/rook/blob/master/deploy/examples/external/cluster-external.yaml

**Comment by mnaser** [comment]
https://github.com/vexxhost/atmosphere/pull/1896
