### ISSUE TITLE
Missing docs for cloudflare solver

### ISSUE THREAD

**Issue by guilhermesteinmuller** [vexxhost/atmosphere#1612]
we have [implemented](https://github.com/vexxhost/atmosphere/commit/08f7be68c77534c5e7ee962d4609c3fa34dd2dac) but we dont have docs here https://vexxhost.github.io/atmosphere/deploy/certificates.html

**Comment by mnaser** [comment]
@fitbeard I can pick this up but maybe if you have a few spare moments to push some docs for that, I think I remember you contributed this :)

**Comment by fitbeard** [comment]
Sure. Assign this to me.
