### ISSUE TITLE
SRIOV and vGPU devices can't be discover by nova-compute

### ISSUE THREAD

**Issue by yaguangtang** [vexxhost/atmosphere#1677]
From https://github.com/search?q=repo%3Aopenstack%2Fnova%20%22%2Fsys%2Fclass%22&type=code we know that nova-compute needs to access /sys/class to discovery NIC VF and vGPU devices, but the nova helm doesn't mount this host directory .

**Comment by mnaser** [comment]
@yaguangtang Do you think we should mount this by default for all deployments?

**Comment by okozachenko1203** [comment]
we can mount any path via `nova_helm_values` https://opendev.org/openstack/openstack-helm/src/branch/master/nova/values.yaml#L2281-L2285
