### ISSUE TITLE
Remove policy from OpenStack Helm charts

### ISSUE THREAD

**Issue by mnaser** [vexxhost/atmosphere#171]
There is a big majority of OpenStack Helm charts that still have hard-coded policy, this is no longer needed and it causes unnecessary log messages.

**Comment by ricolin** [comment]
review link: https://review.opendev.org/c/openstack/openstack-helm/+/865347

**Comment by okozachenko1203** [comment]
handled by https://github.com/vexxhost/atmosphere/commit/bcdd25c47fc1f254b4375829b247dc7bc9243db7
