### ISSUE TITLE
Haproxy for k8s, hit rate limit

### ISSUE THREAD

**Issue by mpiscaer** [vexxhost/atmosphere#179]
When installing k8s I hit the dockerhub ratelimit. "429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit."

https://github.com/vexxhost/atmosphere/blob/main/roles/kubernetes/files/haproxy.yaml#L8 is using dockerhub for haproxy. This needs or configurable or a diffrent repository that don't have the ratelimit.

In the current network too many users are using dockerhub at the same time.

**Comment by mnaser** [comment]
We're working on a major effort to have an internal registry to the deployment... will keep you updated

**Comment by mpiscaer** [comment]
This haproxy is deployed at the moment k8s get installed.

**Comment by mnaser** [comment]
It's now possible to use an external registry for all images which should solve this.

https://github.com/vexxhost/atmosphere/blob/main/docs/user-guide/custom-registry.md
