### ISSUE TITLE
Certificates

### ISSUE THREAD

**Issue by mpiscaer** [vexxhost/atmosphere#182]
I hope that someone can help me with this, I think I have a issue with certs.

In my dev env is use the following config
cert_manager_acme_server: https://stepca.ADDRESS.TLD/acme/acme/directory
atmosphere_issuer_config:
  email: EMAIL@ADDRESS.nl
  server: "{{ cert_manager_acme_server }}"

This works fine without any problem.

On the fieldtest server, since the new release the tasks fails:
```
TASK [vexxhost.atmosphere.certificates : Wait till the secret is created] *************************************************************
ok: [fctrko1.maas]

TASK [vexxhost.atmosphere.certificates : Copy CA certificate on host] *****************************************************************
fatal: [fctrko1.maas]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: list object has no element 0\n\nThe error appears to be in '/home/gitlab-runner/.ansible/collections/ansible_collections/vexxhost/atmosphere/roles/certificates/tasks/main.yml': line 31, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Copy CA certificate on host\n      ^ here\n"}

```

When using the following config:
```
atmosphere_issuer_config:
  type: self-signed
```

When I use a signed public certificated with the following config:

```
atmosphere_issuer_config:
  type: ca
  certificate: |
  .....
  private_key: |
  .....

```    

It fails with the same error.

The log of the Operator pod:

``
```
2022-11-16 17:13.46 [info     ] Ensured resource               kind=HelmRelease name=rabbitmq-cluster-operator namespace=openstack requires=['helm-repository-openstack-bitnami', 'helm-release-cert-manager-cert-manager', 'namespace-openstack']
Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/pykube/http.py", line 438, in raise_for_status
    resp.raise_for_status()
  File "/app/.venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://10.96.0.1:443/apis/cert-manager.io/v1/namespaces/openstack/issuers/openstack?fieldManager=atmosphere-operator&force=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/bin/atmosphere-operator", line 6, in <module>
    sys.exit(main())
  File "/app/atmosphere/cmd/operator.py", line 15, in main
    engine.run()
  File "/app/.venv/lib/python3.10/site-packages/taskflow/engines/action_engine/engine.py", line 247, in run
    for _state in self.run_iter(timeout=timeout):
  File "/app/.venv/lib/python3.10/site-packages/taskflow/engines/action_engine/engine.py", line 340, in run_iter
    failure.Failure.reraise_if_any(er_failures)
  File "/app/.venv/lib/python3.10/site-packages/taskflow/types/failure.py", line 338, in reraise_if_any
    failures[0].reraise()
  File "/app/.venv/lib/python3.10/site-packages/taskflow/types/failure.py", line 350, in reraise
    raise value
  File "/app/.venv/lib/python3.10/site-packages/taskflow/engines/action_engine/executor.py", line 52, in _execute_task
    result = task.execute(**arguments)
  File "/app/atmosphere/tasks/kubernetes/base.py", line 76, in execute
    resource.api.raise_for_status(resp)
  File "/app/.venv/lib/python3.10/site-packages/pykube/http.py", line 445, in raise_for_status
    raise HTTPError(resp.status_code, payload["message"])
pykube.exceptions.HTTPError: issuers.cert-manager.io "openstack" is forbidden: User "system:serviceaccount:openstack:atmosphere" cannot patch resource "issuers" in API group "cert-manager.io" in the namespace "openstack"
```

**Comment by mnaser** [comment]
@mpiscaer is it possible that the image you're running is not up to date?

I think we've got an issue here where we need to restart the operator once we make changes to the config.  we're not actually creating an issuer anymore but we're creating a cluster issuer at this point.

**Comment by mpiscaer** [comment]
I did a reinstall this morning of this cluster.

    Container ID:   containerd://b2c31f1d26e0aee603fd0b58fc8f34c61f8120aec750a6f4781db507531fdeab
    Image:          quay.io/vexxhost/atmosphere:0.6.1
    Image ID:       quay.io/vexxhost/atmosphere@sha256:be9c0209a2b7c07cf1d4704dc166e8a1edf9633c3fde7f41d5f1a5988c2c4790

**Comment by mpiscaer** [comment]
When I use a fresh build of the Atmosphere that is build by molecule is looks like it works beter.

**Comment by thywyn** [comment]
Molecule builds tmp image on ttl.  On the nodes themselves I get this error:
`sudo crictl pull quay.io/vexxhost/atmosphere:0.7.0
E1116 19:05:40.254578   97424 remote_image.go:238] "PullImage from image service failed" err="rpc error: code = NotFound desc = failed to pull and unpack image \"quay.io/vexxhost/atmosphere:0.7.0\": failed to resolve reference \"quay.io/vexxhost/atmosphere:0.7.0\": quay.io/vexxhost/atmosphere:0.7.0: not found" image="quay.io/vexxhost/atmosphere:0.7.0"
FATA[0000] pulling image: rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/vexxhost/atmosphere:0.7.0": failed to resolve reference "quay.io/vexxhost/atmosphere:0.7.0": quay.io/vexxhost/atmosphere:0.7.0: not found`

**Comment by mpiscaer** [comment]
When I was testing it is was still 0.6.1. I can imagine that 7.0.0 not yet build / uploaded yet.

**Comment by thywyn** [comment]
my role default is 0.7.0 here: 
https://github.com/vexxhost/atmosphere/blob/c085b37ae25a8fa19d0410423ae50e387b45278a/roles/atmosphere/defaults/main.yml#L1

**Comment by mpiscaer** [comment]
I also don't see the 0.7.0. in the list of images https://quay.io/repository/vexxhost/atmosphere?tab=tags&tag=latest @mnaser or @guilhermesteinmuller can you clarify?

**Comment by thywyn** [comment]
built 0.7.0 image locally and uploaded to internal image repo.. pointing 'atmosphere_image' variable to that location and stuff is working

**Comment by mnaser** [comment]
sorry, we built the 0.7.0 image and it's working well now.
