### ISSUE TITLE
Keycloak ingress annotations not being used

### ISSUE THREAD

**Issue by umutlelek** [vexxhost/atmosphere#1839]
**How is it now?**

In the file, the “ingress_annotations:” is used in the line shown below.
https://github.com/vexxhost/atmosphere/blob/16b2535242811fa6cea80b14b04aeea2781caf07/roles/keycloak/tasks/main.yml#L102-L103

However, “ keycloak_ingress_annotations: {} ” is used here.

https://github.com/vexxhost/atmosphere/blob/16b2535242811fa6cea80b14b04aeea2781caf07/roles/keycloak/defaults/main.yml#L23

**What is our goal?**

Our goal is to ensure that the configuration for Ingress annotations is used consistently and correctly in both files. We want to check that these variables are linked correctly and, if necessary, make adjustments to ensure a consistent configuration.

**How do we proceed?**

We proceed by adding line 103 from the tasks/main.yml to line 23 from the default/main.yml file. We also set “keycloak_ingress_annotations” in line 23 of the tasks/main.yml file. This means that the variable in “tasks” is still functional and the variable is also set in “default”.

**Comment by mnaser** [comment]
Hi @umutlelek  -- that's a good catch, are you able to submit a PR?
