### ISSUE TITLE
wildcard certificat

### ISSUE THREAD

**Issue by mpiscaer** [vexxhost/atmosphere#206]
I would like to use a wildcard certificate to have all the service running.

Like 
*  https://identity.openstack.domain.tld/v3 -> keystone
*  https://image.openstack.domain.tld/ -> Glance
*  https://openstack.domain.tld/ -> Horzion

**Comment by mpiscaer** [comment]
I created a secret with `kubectl -n openstack create secret tls cert-tls --key="tls.key" --cert="tls.crt"` and changed `openstack_helm_ingress_secret_name: cert-tls`

After running the playbooks the system deletes and recreates a new secret.

**Comment by okozachenko1203** [comment]
https://github.com/vexxhost/atmosphere/blob/223eb5bf031b30152b8972caf137cc58c8ee45fe/roles/openstack_helm_ingress/vars/main.yml#L16

All ingresses have explicit issuer spec in their annotation regardless of certificate type.
It will trigger certificate issue on cert-manager side and user's custom wildcard cert secret is overridden by generated one.

Need to make that annotation configurable.

**Comment by mnaser** [comment]
this is now possible by using this:

https://github.com/vexxhost/atmosphere/blob/a5902dd42117b273cec41ef1be2e12d0279ff817/roles/openstack_helm_ingress/README.md
