### ISSUE TITLE
Set dependencies between helmreleases

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/atmosphere#240]
We introduced 2 following major changes in atmosphere deployment
- use flux and helmrelease
- use k8s operator with taskflow

These are very cool but introduced a frequent deployment failure problem because we don't control the dependencies between helmreleases properly and helmrelease has finite retries. Once an helmrelease is failed to reconcile and install retries exhausted, it is not redeployed at the next deployments.
The fix is just to remove the exhausted helmreleases manually so the atmosphere operator creates them again in the next reconcile loop.

As a workaround, we can increas the retries limit of helmreleases or set it as infinite till we have the proper dependency graph.

**Comment by mnaser** [comment]
I think the plan here is to get rid of task flow and use a combination of simple retries inside Python + `dependsOn` inside HelmRelease.

**Comment by okozachenko1203** [comment]
there is another kind of exhaust which cannot be solved by dependsOn. I faced the following several times in my lab.
Dependency was resolved for Helmreleases but retries were exhausted because it took a bit long time to pull images.
So I had to access to a ctl node and run `flux suspend helmrelease_name` then `flux resume helmrelease_name` to reconcile helmrelease again.

**Comment by mnaser** [comment]
We're dropping the operator towards Ansible-only driven code, so closing this.
