### ISSUE TITLE
Magnum images not using the mirrored images.

### ISSUE THREAD

**Issue by mpiscaer** [vexxhost/atmosphere#266]
The variable for the Magnum images that are 'generated' in atmosphere_images are not used by Magnum, Magnum only uses the IMAGE_LIST.

https://github.com/vexxhost/atmosphere/blob/a3024f6215ce48bc9001e5c67c5f87b39af3d8e2/roles/defaults/defaults/main.yml#L86-L88

**Comment by mnaser** [comment]
You're right, this is because at the moment, it's deployed by the operator which isn't using the new lookups.  Let me fix this.

**Comment by mnaser** [comment]
@mpiscaer this has been resolved in the latest `main` now.
