### ISSUE TITLE
Add documentation for using internal CA

### ISSUE THREAD

**Issue by mnaser** [vexxhost/atmosphere#31]
There are use cases where users would want to use their own CA, such as in https://github.com/vexxhost/atmosphere/discussions/30.

We are already able to handle those cases today, however, there is no documentation to explain this.  We should update our documentation here:

https://github.com/vexxhost/atmosphere/blob/main/docs/certificates.md

In order to include another section on how to use a pre-existing CA which we can use to sign certificates.

**Comment by okozachenko1203** [comment]
i am on it
