### ISSUE TITLE
Prometheus using emptydir instead of persistence 

### ISSUE THREAD

**Issue by guilhermesteinmuller** [vexxhost/atmosphere#352]
We should set prometheus to use persistence so it stores data inside the storage cluster and doest take local storage from controllers

**Comment by mnaser** [comment]
This is starting to become more of an issue as we are scraping more and more metrics in the monitoring.

1. We are running out of space on contollers
2. The solution involves losing data, so not a good time.

We need to explore either #524 but before that, we need to understand why we have so much data in the first place.

**Comment by mnaser** [comment]
For `ethtool`, we are seeing around an average of 1000 records per system with some systems having almost 10K records per host... leading to envs with almost 50K records...

That's a lot of data for us to only need this...

https://github.com/vexxhost/atmosphere/blob/c8785e0def34d628e9e4d53fb835a38246f9189f/roles/kube_prometheus_stack/files/jsonnet/legacy.libsonnet#L10

**Comment by mnaser** [comment]
A workaround for environments where https://github.com/vexxhost/atmosphere/commit/3a0cc7582ae830efd2469f26132f2141417b0955 is not deployed yet is to run this:

```bash
kubectl -n monitoring delete podmonitor/ethtool-exporter
kubectl -n monitoring delete ds/ethtool-exporter
```

of course, in the next deployment, it will go boom, but something to keep in mind.
