### ISSUE TITLE
Hitless Neutron control plane restarts

### ISSUE THREAD

**Issue by mnaser** [vexxhost/atmosphere#353]
In an environment with a large number of networks or routers, the current start up time for the DHCP and L3 agent respectively can get out of hand and it can take a long time for virtual routers to go up.  This is a very long and painful process when you're simply looking to do an upgrade of a Neutron service and don't want to end up restarting your entire data plane of `keepalived` and `dnsmasq` processes.

In addition, at the moment, there is no proper start up probe but a very long readiness check timer, this is not a guaranteed way of doing a rollout and it is possible that this would result in the next replica being rolled out before the first one is done and it would result in an outage since all the data plane components are already wiped.

The solution is two pronged:

1. Leverage the same toolkit which `libvirt` uses to 'break-out' of a Kubernetes pod, this means that when the pod starts, it will run inside a [transient unit on the host](https://github.com/openstack/openstack-helm-infra/blob/master/libvirt/templates/bin/_libvirt.sh.tpl#L183-L184), while making sure that it [kills any leftover process](https://github.com/openstack/openstack-helm-infra/blob/master/libvirt/templates/bin/_libvirt.sh.tpl#L19-L32) on start up but also using a [`preStop`](https://github.com/openstack/openstack-helm-infra/blob/master/libvirt/templates/daemonset-libvirt.yaml#L159-L166) hook to make sure that it terminates it safely.  Once the pod dies, the PIDs all remain running on the host, and if they need to be removed, Neutron will manage and handle that.  This means that you can restart the L3 or DHCP agent safely and the processes will continue to run, the same way it's done in `libvirt`.
2. Investigate into the possibility of implementing a standardized `startupProbe` for data plane agents (such as DHCP & L3) to mark as ready only once they finished syncing.

Completing item 1 is way easier than 2, so I think effort going into that first would be productive.  It would mean one "painful" update would be left if 2 is not done, but depending on how things work, it might be trivial or not to check if the agent is synced.

**Comment by okozachenko1203** [comment]
@mnaser 
- If i understood scope units correctly, it doesn't fork off processes on its own. So in the openstack dataplane agents, `dnsmasq` and `keepalived` processes are not forked from agent processes and it means pod restart will not include those processes(`dnsmasq`, `keepalived`) restart?

- If so, how can we recreate those processes(`dnspasq`, `keepalived`)? There is no such a case?

- I am bit confused about this sentence. It means there should be any order for replicas to be ready? Those all agents run as daemonset so not sure what means `next` replica?
Also those agents are all stateless so not exactly sure that `sync` means?
> In addition, at the moment, there is no proper start up probe but a very long readiness check timer, this is not a guaranteed way of doing a rollout and it is possible that this would result in the next replica being rolled out before the first one is done and it would result in an outage since all the data plane components are already wiped

**Comment by mnaser** [comment]
https://github.com/openstack/neutron/blob/bf568cb24ef824e60bc42258a95edbb49ed29ea4/neutron/agent/l3/agent.py#LL316C19-L316C41

We can detect this to see that comms to server is up, and perhaps interpolate that number...

**Comment by mnaser** [comment]
https://github.com/openstack/neutron/blob/bf568cb24ef824e60bc42258a95edbb49ed29ea4/neutron/agent/l3/agent.py#L870

`self.fullsync` is the key here

**Comment by mnaser** [comment]
could also rely on making sure `fetch_and_sync_all_routers` is running all the time

**Comment by mnaser** [comment]
We can potentially close this with a note saying that we won't be able to support this and you should use OVN when that's out #492

**Comment by mnaser** [comment]
The incoming move to OVN makes this a moot point, closing this.
