### ISSUE TITLE
Manila Instance has other ports open that are not NFS related

### ISSUE THREAD

**Issue by thywyn** [vexxhost/atmosphere#393]
After creating an NFS share.  Ports 137-139/tcp and 445/tcp are open and respond... 5985 and 5986 are open but don't respond and ICMP is open.  Manila's current config does not have SMB enabled.  There is also no way to control access to those ports from a "member" role point of view.

Can we please disable these ports until SMB share is going to be supported and/or configured?

**Comment by mnaser** [comment]
https://github.com/openstack/manila/blob/master/manila/share/drivers/service_instance.py#L350

we can simply pre-create the security group with nfs + icmp only

**Comment by ricolin** [comment]
I think what we need to do is to introduce following to Atmosphere 
openstack security group create manila-service
openstack security group rule create --protocol icmp --ingress manila-service
openstack security group rule create --protocol tcp --dst-port 22:22 manila-service
openstack security group rule create --protocol tcp --dst-port 111:111 manila-service
openstack security group rule create --protocol tcp --dst-port 2049:2049 manila-service

And expose that to [gereric] in manila.conf
service_instance_security_group = manila-service

small change which I can do it, but need to clean some task in my hand before jump into this.

**Comment by mnaser** [comment]
This doesn't work properly because it seems that `service_instance_security_group` has to be the security group name and not the security group ID.

The result is that a security group gets generated with the same exact name as the UUID of the cloud.  We should be passing the name to that config instead of the ID.
