### ISSUE TITLE
Manila - UI reporting incorrect volume quota

### ISSUE THREAD

**Issue by iPenguin** [vexxhost/atmosphere#395]
Hi, 

In the image below you can see 19 of 50 used shares. However the 19 shares are created in the service project which has a 20 share quota.

<img width="406" alt="Screenshot_20230426_153926" src="https://user-images.githubusercontent.com/152118/234913810-b045b4f1-8d5d-41c6-9d1c-d2cacd527216.png">

I'm not sure where the 50 is coming from. I changed the project's volume quota to 15 as a test and it's still showing 50 in the UI. When I tried to create the 19th share there was an error because the service project's quota (20) has been reached. 

It looks like there are two volumes for the VMs providing the NFS service that count against the quota (which is not intuitive because they are not displayed in the list of shares or volumes).

Given that the shares are created in the service project it would be nice if the UI showed the quota for the service project as the maximum.

A better solution would be if the volumes were counted in the current project and the UI showed the current project's count and quota.

Thanks,
Brian

**Comment by mnaser** [comment]
The issue was Cinder quota for the service project was not correct.  Closing in favour of #397
