### ISSUE TITLE
Enforce source IP for Octavia Amphorae

### ISSUE THREAD

**Issue by mnaser** [vexxhost/atmosphere#413]
It seems that at the moment when using Octavia, it's possible that the source IP is not the same as the IP address that sends traffic to the backends, this makes it hard for security purposes to identify and lock down traffic coming in from the Amphora itself specifically.

**Comment by okozachenko1203** [comment]
> It seems that at the moment when using Octavia, it's possible that the source IP is not the same as the IP address that sends traffic to the backends, this makes it hard for security purposes to identify and lock down traffic coming in from the Amphora itself specifically.

@mnaser do you mean the source ip is changed by amphora ip because of SNAT but this replaced amphora ip is incorrect?

**Comment by mnaser** [comment]
@okozachenko1203 well, if you are using ACTIVE_STANDBY, you will have 2x amphora with each an IP address... and then the VRRP VIP..

When traffic goes from the ACTIVE LB, the source IP of the traffic to the instance will be the Amphora IP and not the VRRP IP, which means if you are trying to create a "filter" to allow the LB traffic only.. it's impossible because you don't know what that IP address is.. the only IP you know is the VIP IP.

**Comment by okozachenko1203** [comment]
https://storyboard.openstack.org/#!/story/2010778

**Comment by mnaser** [comment]
Upon further discussion, it might make sense to actually create a security group automatically when the load balancer is created that the user can attach to their VMs in order to generate connectivity to the VM.

**Comment by okozachenko1203** [comment]
upstream bug report and patch for this 
https://bugs.launchpad.net/octavia/+bug/2016475
https://review.opendev.org/c/openstack/neutron/+/877533

**Comment by okozachenko1203** [comment]
https://review.opendev.org/c/openstack/octavia/+/893943
https://review.opendev.org/c/openstack/octavia/+/893942
https://review.opendev.org/c/openstack/octavia/+/893941
https://review.opendev.org/c/openstack/octavia/+/893780
https://review.opendev.org/c/openstack/octavia/+/893941

**Comment by mnaser** [comment]
@okozachenko1203 this is great progress, seems like we'll be able to get this in soon!

**Comment by mnaser** [comment]
Our newest images have this fix in.
