### ISSUE TITLE
OpenStack-Exporter Version

### ISSUE THREAD

**Issue by runlevel-six** [vexxhost/atmosphere#44]
I noticed that https://quay.io/repository/niedbalski/openstack-exporter-linux-amd64?tab=tags does not have a tag v1.6.0 which is the image and tag referenced in `roles/openstack-exporter/defaults/main.yml`. There is a v1.5.0 tag and that one works fine in the Atmosphere plays when I overwrite the variable.

**Comment by mnaser** [comment]
👋 @runlevel-six 

good catch, I've noticed that in my local environment with it crash looping.

**Comment by mnaser** [comment]
It looks like the project has moved to using GitHub packages:

https://github.com/openstack-exporter/openstack-exporter/pkgs/container/openstack-exporter
