### ISSUE TITLE
`openstacksdk` support for Python 3.6 broken

### ISSUE THREAD

**Issue by mnaser** [vexxhost/atmosphere#464]
It seems that a recent commit has broken Python 3.6 support.

https://github.com/openstack/openstacksdk/commit/3cb5bc98573e8eb7d3487121b7b59ebd535035c5

We should push upstream to fix this and then push for a follow-up release.

**Comment by ricolin** [comment]
start the works here now https://review.opendev.org/c/openstack/openstacksdk/+/887137

**Comment by haligan** [comment]
Ok thanks!

I'll keep an eye on it; if I can help I'll jump in, or please let me know what I can do.

**Comment by mnaser** [comment]
openstacksdk 1.3.1 with the fix has been released. 

Good stuff @ricolin
