### ISSUE TITLE
openvswitch poststart hook crashes pod

### ISSUE THREAD

**Issue by adamhackl** [vexxhost/atmosphere#465]
We ran into an issue where in some cases, openvswitch pod is failing continually in a crashloopbackoff. After some investigation, it appears that this is a timing issue in regards to the poststart hook. It appears that it may be trying to chown the control socket file before the file is created by the ovs-vswitchd command in the start function, causing a failure.

Errors look like:
```
  Warning  FailedPostStartHook  33m                 kubelet            Exec lifecycle hook ([/tmp/openvswitch-vswitchd.sh poststart]) for Container "openvswitch-vswitchd" in Pod "openvswitch-zmvth_openstack(50a3047f-7f62-4f91-aaa9-bdbe45247da0)" failed - error: command '/tmp/openvswitch-vswitchd.sh poststart' exited with 1: + COMMAND=poststart
+ OVS_SOCKET=/run/openvswitch/db.sock
+ OVS_PID=/run/openvswitch/ovs-vswitchd.pid
+ poststart
++ cat /run/openvswitch/ovs-vswitchd.pid
cat: /run/openvswitch/ovs-vswitchd.pid: No such file or directory
+ PID=
, message: "+ COMMAND=poststart\n+ OVS_SOCKET=/run/openvswitch/db.sock\n+ OVS_PID=/run/openvswitch/ovs-vswitchd.pid\n+ poststart\n++ cat /run/openvswitch/ovs-vswitchd.pid\ncat: /run/openvswitch/ovs-vswitchd.pid: No such file or directory\n+ PID=\n"
  Normal   Killing            33m  kubelet  FailedPostStartHook
  Warning  FailedPreStopHook  33m  kubelet  Exec lifecycle hook ([/tmp/openvswitch-vswitchd.sh stop]) for Container "openvswitch-vswitchd" in Pod "openvswitch-zmvth_openstack(50a3047f-7f62-4f91-aaa9-bdbe45247da0)" failed - error: command '/tmp/openvswitch-vswitchd.sh stop' exited with 1: + COMMAND=stop
+ OVS_SOCKET=/run/openvswitch/db.sock
+ OVS_PID=/run/openvswitch/ovs-vswitchd.pid
+ stop
++ cat /run/openvswitch/ovs-vswitchd.pid
+ PID=41
+ ovs-appctl -T1 -t /run/openvswitch/ovs-vswitchd.41.ctl exit
2023-06-27T18:58:23Z|00001|unixctl|WARN|failed to connect to /run/openvswitch/ovs-vswitchd.41.ctl
ovs-appctl: cannot connect to "/run/openvswitch/ovs-vswitchd.41.ctl" (No such file or directory)
, message: "+ COMMAND=stop\n+ OVS_SOCKET=/run/openvswitch/db.sock\n+ OVS_PID=/run/openvswitch/ovs-vswitchd.pid\n+ stop\n++ cat /run/openvswitch/ovs-vswitchd.pid\n+ PID=41\n+ ovs-appctl -T1 -t /run/openvswitch/ovs-vswitchd.41.ctl exit\n2023-06-27T18:58:23Z|00001|unixctl|WARN|failed to connect to /run/openvswitch/ovs-vswitchd.41.ctl\novs-appctl: cannot connect to \"/run/openvswitch/ovs-vswitchd.41.ctl\" (No such file or directory)\n"
  Warning  BackOff  3m27s (x154 over 33m)  kubelet  Back-off restarting failed container
```

We were able to resolve it by adding in a short sleep at the beginning of the poststart function, but I assume that the correct fix would be to add a wait for the file before changing permission.

Relevant section from openvswitch-bin configmap:
```
    function poststart () {
      # This enables the usage of 'ovs-appctl' from neutron-ovs-agent pod.

      sleep 10 #we added this as a temp fix
      PID=$(cat $OVS_PID)
      OVS_CTL=/run/openvswitch/ovs-vswitchd.${PID}.ctl
      # There should be a check here to confirm the file exists?
      chown 42424.42424 ${OVS_CTL}
    }

```

**Comment by ricolin** [comment]
Hi @adamhackl thanks for the detail investigate.
I created patch in openstack/openstack-helm-infra now and will move it to Atmosphere asap 
https://review.opendev.org/c/openstack/openstack-helm-infra/+/887203

**Comment by mnaser** [comment]
@ricolin nice, looks like we're in the gate for this, so we'll probably just bump the ovs chart instead of having to maintain a downstream patch.

**Comment by adamhackl** [comment]
In the upstream, it looks like the watch for the PID file was added, but the watch for the control socket file was removed in the last commit. We were having issues with both files, so I think its possible we would still have the issue. There were instances where we didn't have the PID file, and instances where we had the PID, but not the control socket (see my output).

**Comment by mnaser** [comment]
It seems that we're now able to catch a PID file not being there but it is possible that the control file is missing.  We should also make sure the control file goes up as well.

**Comment by ricolin** [comment]
@adamhackl you're right, the ctl file check back then was somehow making check job timeout. And that's why it's separated from the last patch.
I added it back to https://review.opendev.org/c/openstack/openstack-helm-infra/+/887986 now. 
Will push that one ASAP

**Comment by mnaser** [comment]
seems like that was landed, good stuff.

**Comment by mnaser** [comment]
@adamhackl: https://github.com/vexxhost/atmosphere/commit/254721f842913498bc9c16c46fc8c62e2b45ab20 should be good for the fix :)

**Comment by ricolin** [comment]
Nevermind, I will close that pull request :)
