### ISSUE TITLE
OVN support

### ISSUE THREAD

**Issue by mnaser** [vexxhost/atmosphere#492]
OVN brings a lot of advantages to the table, but we have a few issues in order to be able to present feature parity:

- [ ] [VPNaaS support](https://review.opendev.org/c/openstack/neutron-vpnaas/+/765353)
- [ ] [Ability to override Geneve port](https://bugzilla.redhat.com/show_bug.cgi?id=1720371) (since we use Geneve for Cilium)

The dependent work items for this are as follows:

- [x] https://github.com/vexxhost/atmosphere/issues/493

Once we have that in place, we can start integrating things with these work items

- [ ] Add option with `neutron_plugin` that defaults to `ml2` inside the `roles/defaults/defaults.yml`
- [ ] Add an `ovn` role which runs when `neutron_plugin` is set to `ovn` that includes deploying the Helm chart
- [ ] Make modifications to the Neutron role to automatically disable the extra components and integrate Neutron with OVN
- [ ] Implement a mechanism to block changing `neutron_plugin` so things don't break
- [ ] Stretch goal: Add code to allow migrating from ML2/OVS to OVN (but not back to ML2/OVS).

**Comment by mnaser** [comment]
It seems someone else had the idea of using VXLAN:

https://bugzilla.redhat.com/show_bug.cgi?id=1881704
https://www.mail-archive.com/ovs-discuss@openvswitch.org/msg06771.html
https://patchwork.ozlabs.org/project/openvswitch/patch/20200320050711.247351-1-ihrachys@redhat.com/

but it provides limitations:

https://github.com/ovn-org/ovn/commit/b07f1bc3d068e231e40840b0d977bd57158987fd

**Comment by mnaser** [comment]
bingo.

https://docs.cilium.io/en/latest/helm-reference/

we can override `tunnelPort` and move Cilium to another port, which means we can let OVS use the main port for Geneve and go as is.

**Comment by fitbeard** [comment]
@mnaser
OVN support link is broken.
Can you explain ceph-ml2/ovn with more details?

Right now I’m working on fool rook support WIP. Will publish WIP PR in future.

**Comment by mnaser** [comment]
@fitbeard : sorry about that -- i've fixed/updated it.

also i meant that since we have a ceph aio job https://github.com/vexxhost/atmosphere/blob/main/.github/workflows/ceph.yml -- but we'd run that for both ml2/ovs and ovn as well

**Comment by mnaser** [comment]
So, at this point:

- [OVN images are built](https://github.com/vexxhost/docker-ovn)
- OVN charts are tested locally but need to add a role to handle them

What is outstanding:

- https://github.com/vexxhost/atmosphere/issues/493
- We need to integrate Neutron with the OVN deployment if OVN is enabled
- We need to change the ceph scenario to become ceph-ml2 and introduce a new ceph-ovn scenario

**Comment by mnaser** [comment]
A small follow-up note is to make sure DNS is configured appropriately:

```
[ovn]
dns_servers = 203.0.113.8, 198.51.100.53
```

**Comment by mnaser** [comment]
Good progress. 2 more steps:

- We need to integrate Neutron with the OVN deployment if OVN is enabled
- We need to change the ceph scenario to become ceph-ml2 and introduce a new ceph-ovn scenario

**Comment by mnaser** [comment]
success .. https://github.com/vexxhost/atmosphere/pull/499

we'll need to test this in a multi-node scenario but we should be good :)
