### ISSUE TITLE
Keycloak support

### ISSUE THREAD

**Issue by mnaser** [vexxhost/atmosphere#496]
One of the things that we need to accomplish is having proper SSO and authentication within OpenStack.  The plan is to enable Keycloak to be the primary source of truth for authentication for the cloud and all the different components, such as OpenStack dashboard, Grafana, etc.

There are a few components that we need to do in order to successfully complete this:

- [x] Deploy Keycloak (either using the operator or the Helm charts)
- [x] Setup an "Atmosphere" realm within Keycloak out of the box
- [x] Create clients for the different components (such as OpenStack dashboard, Grafana, etc)
- [x] Integrate all of the components with Keycloak for authentication
- [x] Add documentation to integrate external identity providers (such as Azure AD)

There are a few things that I think we need to be careful about:

We need to find a way to make sure that if a user gets deactivated/disabled, we do that in the other services.   We need to make sure if we disable a user inside of Keycloak, it should deactivate it in all the other systems such as Grafana & OpenStack.

We should also make sure Keycloak is opt-in only as well, because we don't want to break existing deployments, but I believe the long term plan is for things to MOVE towards native Keycloak auth only (probably at some point when we have a major release).

**Comment by okozachenko1203** [comment]
- I agree, I bet once we use keycloak operator, such realm, clients, etc. can be managed by CRDs.
- This auth integration includes keystone OIDC with keycloak. i.e. not only GUIs such as grafana and horizon, all openstack API requests will be authed by keycloak using OIDC. I think it is feasible to deactivate already-issued oidc tokens as long as their lifespan is not expired.

**Comment by mnaser** [comment]
I've been thinking about how we can get this done cleanly over the past few days and I think I have reached to a pretty good spot about how it can be handled:

- [ ] Build a new Keystone identity backend: `keycloak` 

    This should use the [Keycloak Admin REST API](https://www.keycloak.org/docs-api/18.0/rest-api/) in order to pull in all of the users/groups from Keycloak, the primary reasons for this would be for the purposes of disabling a user in Keycloak and it would automatically disable in the other OpenStack.  It would also mean that the second a user "exists" in Keycloak, it will automatically exist in OpenStack and we don't need wonky syncing.

- [ ] Deploy Keycloak using the operator inside Atmosphere

    With this, we'll be able to deploy the initial deployment of Keycloak and it will allow us to pave the path to be integrated, we should also probably create a realm called `atmosphere` to get all of this working properly.

- [ ] Integrate OpenStack with Keycloak

    In order for the integration to work in both ways, we would implement Keystone to use the new identity backend which interfaces with Keycloak and then create a client for Horizon/Keystone inside OpenStack, with the default domain being `atmosphere`.  This closes the loop of Keycloak/Keystone/Horizon entirely and then users can be allowed to use Keycloak for authentication.  Note that with this behaviour, it will still be required for Keystone to be the assignment source (aka you will need to assign Keycloak groups/users to projects in Keystone).

- [ ] Integrate Grafana with Keycloak

    Since we want to wrap up the entire authentication process, we should implement Grafana natively too, which means SSO for all of Atmosphere should be possible across the entire stack.  Any exposed service that we share should be available to be accessed natively using it.

I think this will allow us to build a nice solution.  The only missing piece is assigning projects to users, this can be done as a follow up of adding an extra `assignment` provider inside Keystone and implementing this part, but that's probably something for the future.

**Comment by mnaser** [comment]
I've started the first stage and the "basics" are done.

https://github.com/vexxhost/keystone-keycloak-backend

With a `docker-compose up`, and a `source hack/testrc` -- you'll be able to list users and show a user in the `keycloak` domain which will be pulling users over the Admin API.

We just need to get the rest of the methods in and we'll be able to pull in all the necessary data, enabling Keystone to simply rely on Keycloak for all users and groups and only providing assignment (as if it would if we used LDAP).

**Comment by mnaser** [comment]
update on this.. all methods (without any hints) are implemented at the moment, so the backend is functional.  the only missing piece is just implementing the hints which can increase performance and adding some proper ci/release

**Comment by mnaser** [comment]
Just to update here, the `keystone-keycloak-backend` is now released to PyPI which should make it easier to integrate into images.

https://pypi.org/project/keystone-keycloak-backend/

Will work on adding it to our Keystone images soon™

**Comment by okozachenko1203** [comment]
> Just to update here, the `keystone-keycloak-backend` is now released to PyPI which should make it easier to integrate into images.
> 
> https://pypi.org/project/keystone-keycloak-backend/
> 
> Will work on adding it to our Keystone images soon™

I think we can build keystone images inside the `keystone-keycloak-backend` project's gh workflow as we do for magnum in magnum-capi project. So we will have new keystone images whenever we have changes in keycloak-backend

**Comment by mnaser** [comment]
Closing this as complete.
