### ISSUE TITLE
Delete nova-cell-setup job

### ISSUE THREAD

**Issue by guilhermesteinmuller** [vexxhost/atmosphere#513]
We should do the same as done here https://github.com/vexxhost/atmosphere/pull/422 to avoid failing deployments

**Comment by mnaser** [comment]
we can make this a `loop`

https://github.com/vexxhost/atmosphere/blob/181f1e9d2a25ca716328112f3e1b1215ac93afeb/roles/nova/tasks/main.yml#L43-L53
