### ISSUE TITLE
K8s version upgrade from 1.24 to 1.27

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/atmosphere#516]
Atmosphere consists of a number of components sticky to k8s version, such as k8s cluster itself and applications running on it. For some of them, dev and release processes are under our control but some of them are out of ours. It means this upgrade will require upstream contributions to here and there as well as atmosphere project update.
The components are as following;
- [ ] Openstack-helm charts
- [ ] Other helm charts (promethes-community, grafana, pxc, etc.)
- [ ] K8s Operators (pxc-operator, cluster-api, rook)
- [ ] ansible modules and collections ([vexxhost.kubernetes](https://github.com/vexxhost/ansible-role-kubernetes), vexxhost.ceph, etc.)

This upgrade is not only for version upgrade in the manifest/catalog but also the runtime upgrade. We need to consider the upgrade process of the pre-existing atmosphere environments.

**Comment by okozachenko1203** [comment]
https://kubernetes.io/blog/2023/04/11/kubernetes-v1-27-release/#deprecations-and-removals

**Comment by mnaser** [comment]
This is already done for now!  We're at 1.28.
