### ISSUE TITLE
Sync OSH upstream

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/atmosphere#528]
Upstream osh is a bit much behind the atmosphere chart manifests.
- [x] ovn(neutron chart) https://github.com/vexxhost/atmosphere/pull/499
- [x] ovn-related (nova chart) https://review.opendev.org/c/openstack/openstack-helm/+/892139
- [x] ovn-related (libvirt chart) https://review.opendev.org/c/openstack/openstack-helm-infra/+/892140
- [x] oidc(keystone chart) https://github.com/vexxhost/atmosphere/pull/510
- [x] netns cleanup and Use same nodeSelector for ovn metadata agent as ovs(neutron chart)  https://github.com/vexxhost/atmosphere/commit/43677f6f3b8745179039ad0dee3f684c8413e9c1 https://github.com/vexxhost/atmosphere/commit/8fa18182f5bc8e0a3ec8fe54b38c896aabf42027 https://review.opendev.org/c/openstack/openstack-helm/+/893733
- [x] vnc tls support(nova chart)  https://opendev.org/openstack/openstack-helm/commit/bee2353cae1ed375ab3705e8e5039bc8fc5dc40a
- [x] vnc tls support(libvirt chart) https://opendev.org/openstack/openstack-helm-infra/commit/f234218dba3cfad36513e7701cabf18a7fde217a#diff-1dfa1babae53c0b9cbe57e6a10f42919786c0a0f https://github.com/vexxhost/atmosphere/issues/557
- [ ] update libvirt tls support(libvirt chart) https://review.opendev.org/c/openstack/openstack-helm-infra/+/893406
- [x] https://github.com/vexxhost/atmosphere/commit/56484d73689f65eb75142bd648ab11dcb24fad4e https://review.opendev.org/c/openstack/openstack-helm/+/892131
- [ ] ovn gateway https://[review.opendev.org/c/openstack/openstack-helm-infra/+/893739](https://review.opendev.org/c/openstack/openstack-helm-infra/+/893739)

**Comment by okozachenko1203** [comment]
https://opendev.org/openstack/openstack-helm/commit/56c4341d8b13ce5074dfaee20fab720e0e4e1592

**Comment by mnaser** [comment]
there is a couple of things that we are not sync'd.. i wonder if it makes sense to maybe create a fork and maintain that.. and then have a script to sync upstream instead?  and then perhaps we inject the charts in build time? @okozachenko1203

**Comment by okozachenko1203** [comment]
> there is a couple of things that we are not sync'd.. i wonder if it makes sense to maybe create a fork and maintain that.. and then have a script to sync upstream instead? and then perhaps we inject the charts in build time? @okozachenko1203

@mnaser well, you mean we have to maintain our own version including permanent diff from the upstream? Or just to have a fork to reflect changes(matching patches will be created at anytime) without need to wait upstream review and merge?
