### ISSUE TITLE
Failing to collect metrics for nova

### ISSUE THREAD

**Issue by guilhermesteinmuller** [vexxhost/atmosphere#534]
We figured that openstack_nova_memory_used_bytes was not reporting anything. 

Looking at openstack-exporter, we found:

```
time="2023-08-17T19:16:58Z" level=error msg="Failed to collect metric for exporter: nova, error: failed to collect metric: running_vms, error: CPUInfo has unexpected type: <nil>" source="exporter.go:123
```

Which pointed us to https://github.com/openstack-exporter/openstack-exporter/issues/268

Essentially we need to add this:

```
env:
        - name: OS_COMPUTE_API_VERSION
          value: "2.87"
```

To be able to allow nova data to be scraped.

**Comment by ricolin** [comment]
Let's wait for the main repo stable so we can run https://github.com/vexxhost/atmosphere/pull/new/use-2.87-nova-api-for-openstack-exporter through before I send a PR
