### ISSUE TITLE
bug: Add information of image build project itself in the container image tag

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/atmosphere#542]
### Descriptioin
Now container image tags only include target project's release and commit hash value but no infor related to build project's.
https://github.com/vexxhost/atmosphere/blob/7b46b46bac204d0f9029d42513a61c87da0a768a/internal/pkg/image_repositories/build_workflow.go#L185-L191
We faced image overriding (i.e specific image digests have been deleted which are consumed by atmosphere head branch) when only build project manifests updated. (for example, https://github.com/vexxhost/docker-openstack-keystone/commit/c427be0b01490c44df079a833ca345a08c3a0725, https://github.com/vexxhost/docker-openstack-keystone/commit/df83bc9f50198d5431872f274d70aadaeb21f53c. In these 2 commits, CI built images using a same tag).
As a result, we faced CI failures in atmosphere because of non-existing image digest. https://github.com/vexxhost/atmosphere/actions/runs/5926478084/job/16069881013?pr=537

### Solution
Add some information related to image build action (for example, image build time or image repository commit hash value) in the image tag.

**Comment by mnaser** [comment]
This is now done natively via Zuul.
