### ISSUE TITLE
pxe haproxy failing

### ISSUE THREAD

**Issue by mpiscaer** [vexxhost/atmosphere#545]
After a slow ceph nodes with slow ops the percona database server was reporting 6,5k Threads connections with a max_connections of 8192.

The readiness and liveness of the pxe haproxy where failing, probably /usr/local/bin/check_pxc.sh was reporting that the system was not healthy.

In the current haproxy logs I'm missing timestamps for a proper analyse.

After restart of a mysql member node that was not master the cluster was stable.

**Comment by mnaser** [comment]
@mpiscaer so maybe we can propagate this issue up to the percona xtradb cluster operator to try and detect/improve upon this?

i think it might make sense to jump to mysql 8 at some point soon, im not sure if this will help increase the stability.  we can also perhaps upgrade to latest mysql 5.x ?

what do you think?

**Comment by mpiscaer** [comment]
@mnaser I'm not sure what the rootcase is. I would love to see if we can reproduce the issue. Without the rootcase I don't see any reason to upgrade. Except when we see something in the changelog.

**Comment by mpiscaer** [comment]
We faced the same issue again (non production system) and when running /usr/local/bin/check_pxc.sh I got the following output:

```
bash-4.4$ /usr/local/bin/check_pxc.sh
ERROR 2005 (HY000): Unknown MySQL server host '-P' (-2)
The following values are used for PXC node  in backend :
wsrep_local_state is ; pxc_maint_mod is ; wsrep_cluster_status is ; 3 nodes are available
PXC node  for backend  is not ok
```

**Comment by mpiscaer** [comment]
We hit the same problem again, the problem is that connecting to the galera cluster it takes longer then 1 second.

This will fail in the readiness check. In the haproxy health check there is no requirement for a timeout.

Also at from one haproxy this connection goes slow and on the sametime this connection goes fast.

**Comment by mpiscaer** [comment]
In this case the the percona server was unable to resolve the PTR records from the coreDNS pods. This resulted in a timeout.
