### ISSUE TITLE
Sync Libvirt chart

### ISSUE THREAD

**Issue by ricolin** [vexxhost/atmosphere#557]
Some of libvirt changes got merged to community (like https://review.opendev.org/c/openstack/openstack-helm-infra/+/888477)
would be great to sync upstream libvirt charts and bump the version up to 1.23

**Comment by okozachenko1203** [comment]
Here is the sister issue https://github.com/vexxhost/atmosphere/issues/528

**Comment by okozachenko1203** [comment]
https://review.opendev.org/c/openstack/openstack-helm-infra/+/893406

**Comment by okozachenko1203** [comment]
https://[storage.gra.cloud.ovh.net/v1/AUTH_dcaab5e32b234d56b626f72581e3644c/zuul_opendev_logs_94a/893406/6/check/openstack-helm-infra-openstack-support/94a9126/primary/pod-logs/openstack/libvirt-libvirt-default-rd84f/libvirt.txt](https://storage.gra.cloud.ovh.net/v1/AUTH_dcaab5e32b234d56b626f72581e3644c/zuul_opendev_logs_94a/893406/6/check/openstack-helm-infra-openstack-support/94a9126/primary/pod-logs/openstack/libvirt-libvirt-default-rd84f/libvirt.txt)
