### ISSUE TITLE
designate api_paste_config file missing

### ISSUE THREAD

**Issue by mpiscaer** [vexxhost/atmosphere#558]
When using Designate, the api pod gets into CrashLoopBackOff. The logs indicated the following error:
 
designate.exceptions.ConfigurationError: Unable to determine appropriate api-paste-config file

The designate.conf has the following setting:
api_paste_config = /var/lib/openstack/etc/designate/api-paste.ini

I expect that this api-past file is missing.

**Comment by okozachenko1203** [comment]
> When using Designate, the api pod gets into CrashLoopBackOff. The logs indicated the following error:
> 
> designate.exceptions.ConfigurationError: Unable to determine appropriate api-paste-config file
> 
> The designate.conf has the following setting: api_paste_config = /var/lib/openstack/etc/designate/api-paste.ini
> 
> I expect that this api-past file is missing.

Which image do you use? I checked both `quay.io/vexxhost/designate:yoga` and `quay.io/vexxhost/designate:zed` images and both include api-paste file.
```sh
root@1c3184a80c55:/var/lib/openstack/etc/designate# ls
api-paste.ini  rootwrap.conf.sample  rootwrap.d
```

**Comment by mpiscaer** [comment]
Thanks for your response,

I use the following image:
root@stctrko1:~# kubectl -n openstack describe pod/designate-api-7f88656668-tgws2|grep Image
    Image:         regi.c3.cgm.ag/openstack-helm/infra/kubernetes-entrypoint:latest
    Image ID:      regi.c3.cgm.ag/openstack-helm/infra/kubernetes-entrypoint@sha256:ad430737657f9e10ae5ac5708cd7f94dcec6630cfbdd158520b99b7285e253da
    Image:         regi.c3.cgm.ag/openstack-helm/infra/designate@sha256:3f5039753555331c7f3ab8fa9f53206f185752d2cb4c3fa0e05c0b5e18540fa0
    Image ID:      regi.c3.cgm.ag/openstack-helm/infra/designate@sha256:3f5039753555331c7f3ab8fa9f53206f185752d2cb4c3fa0e05c0b5e18540fa0

These are the same images as in https://github.com/vexxhost/atmosphere/blob/main/roles/defaults/vars/main.yml#L49-L55

**Comment by mpiscaer** [comment]
@okozachenko1203 Thanks, indeed the file is there:

user@testnode:~$ docker run -t -i --rm  regi.domain.local/openstack-helm/infra/designate@sha256:3f5039753555331c7f3ab8fa9f53206f185752d2cb4c3fa0e05c0b5e18540fa0 ls -l /var/lib/openstack/etc/designate/api-paste.ini
-rw-r--r-- 1 root root 2626 Jan 30  2023 /var/lib/openstack/etc/designate/api-paste.ini

But https://github.com/openstack/designate/blob/stable/zed/designate/api/service.py#L51 says something like there is something wrong with the config.

Any direction where I can look?

**Comment by okozachenko1203** [comment]
> @okozachenko1203 Thanks, indeed the file is there:
> 
> user@testnode:~$ docker run -t -i --rm regi.domain.local/openstack-helm/infra/designate@sha256:3f5039753555331c7f3ab8fa9f53206f185752d2cb4c3fa0e05c0b5e18540fa0 ls -l /var/lib/openstack/etc/designate/api-paste.ini -rw-r--r-- 1 root root 2626 Jan 30 2023 /var/lib/openstack/etc/designate/api-paste.ini
> 
> But https://github.com/openstack/designate/blob/stable/zed/designate/api/service.py#L51 says something like there is something wrong with the config.
> 
> Any direction where I can look?

@mpiscaer i can see that there are 2 `api_paste_config` in designate config
One is in `Default` optgroup and another is `service:api`.
I can see that code snippet is checking `service:api`(https://docs.openstack.org/designate/2023.1/admin/config.html#service-api) which is not set in our chart.

Could you try again with the additional values?
```yaml
designate_helm_values:
  conf:
    designate:
      service:api:
        api_paste_config: /var/lib/openstack/etc/designate/api-paste.ini
```

**Comment by mpiscaer** [comment]
Thanks, that works a lot better. Should this not be in the [charts](https://github.com/vexxhost/atmosphere/blob/main/charts/designate/values.yaml#L405) or in [Atmosphere](https://github.com/vexxhost/atmosphere/blob/main/roles/designate/vars/main.yml#L15-L27)?

**Comment by okozachenko1203** [comment]
> Thanks, that works a lot better. Should this not be in the [charts](https://github.com/vexxhost/atmosphere/blob/main/charts/designate/values.yaml#L405) or in [Atmosphere](https://github.com/vexxhost/atmosphere/blob/main/roles/designate/vars/main.yml#L15-L27)?

cool. yeah, it should be in upstream and no need to be in the user-defined values.
I will make a new patch to osh upstream. btw, fyi, we will copy default config files(not only paste but also other openstack configs) to `/etc/SERVICE` path so we can offload a lot of default values  redefined in the osh chart values.

**Comment by okozachenko1203** [comment]
https://review.opendev.org/c/openstack/openstack-helm/+/883168/21..22/designate/templates/configmap-etc.yaml
