### ISSUE TITLE
OVN trunk 500 errors

### ISSUE THREAD

**Issue by mnaser** [vexxhost/atmosphere#561]
The following backport was proposed to resolve issues with 500s when using OVN in combination with trunks and newer versions of OVN.

https://review.opendev.org/q/I34caf7d0212ccb4bd7259c4414e7c3994bd8da4d

We need to make sure those merge, and once they do, we build and bump images.

**Comment by mnaser** [comment]
This merged.  Now we need new images.

**Comment by mnaser** [comment]
https://github.com/vexxhost/docker-openstack-neutron/pull/30

**Comment by mnaser** [comment]
fixed

**Comment by guilhermesteinmuller** [comment]
This is deployed in one environment, and users reported success, which means we are good here. I'm closing it
