### ISSUE TITLE
neutron-ovn-metadata fails to start

### ISSUE THREAD

**Issue by guilhermesteinmuller** [vexxhost/atmosphere#567]
Non-deterministically when we restart neutron-ovn-metadata we get this

```
2023-09-06 14:01:12.895 128 ERROR neutron OSError: [Errno 22] failed to open netns
```

Crashing a whole rollout unless we do:

```
ip netns | grep ovnmeta | awk '{print $1}' | xargs -n1 ip netns del
```

And recreate the failing pod

**Comment by okozachenko1203** [comment]
https://bugs.launchpad.net/neutron/+bug/2037102

**Comment by okozachenko1203** [comment]
https://github.com/vexxhost/neutron/pull/1

**Comment by mnaser** [comment]
@okozachenko1203 you will need to pull to branch in the middle like 2023.2 etc

**Comment by mnaser** [comment]
This is fixed with the latest image:

```
ghcr.io/vexxhost/atmosphere/neutron:zed@sha256:e4b51997412d159ceac09b8899eee6ba58565aca0e27d39b57a3ddd56b1c9a9e
```
