### ISSUE TITLE
Keystone/Keycloak SSO: "Could not find user" with new user and inactive, signed in user

### ISSUE THREAD

**Issue by etimmons-sp** [vexxhost/atmosphere#571]
After creating a new user in a Keycloak realm and assigning the user to roles which are mapped properly in Keystone, the user receives a 401 error when trying to sign in.

In the keystone logs, the error "Could not find user" (keystone.exception.UserNotFound) appears:

```sh
XXX.XX.X.XXX - 6c656d46-ebde-486a-bc68-6b8eff290a19@keycloak/realms/12345 [07/Sep/2023:18:30:25 +0000] "GET /v3/auth/OS-FEDERATION/identity_providers/redirect?state=rntvVQaqiXwWwJOa4mXehxFwFGs&session_state=ca6b6848-b8dc-43ca-a65e-3196893826b8&code=79777d3f-dcca-47b7-bd36-76b0efc841f0.ca6b6848-b8dc-43ca-a65e-3196893826b8.b7835a86-c9ee-4110-82df-d3484fabdbd5 HTTP/1.1" 302 355
[Thu Sep 07 18:30:25.908198 2023] [wsgi:error] [pid 6:tid 140298924193344] [remote XXX.XX.X.XXX:37680] 2023-09-07 18:30:25.907 6 WARNING keystone.auth.plugins.core [None req-5b498dd6-5ddb-4039-926f-cc6a3689c901 - - - - - -] Could not find user: 6c656d46-ebde-486a-bc68-6b8eff290a19.: keystone.exception.UserNotFound: Could not find user: 6c656d46-ebde-486a-bc68-6b8eff290a19.\x1b[00m
[Thu Sep 07 18:30:25.929282 2023] [wsgi:error] [pid 6:tid 140298924193344] [remote XXX.XX.X.XXX:37680] 2023-09-07 18:30:25.927 6 WARNING keystone.server.flask.application [None req-5b498dd6-5ddb-4039-926f-cc6a3689c901 - - - - - -] Authorization failed. The request you have made requires authentication. from YYY.YY.YY.YYY: keystone.exception.Unauthorized: The request you have made requires authentication.\x1b[00m
XXX.XX.X.XXX - 6c656d46-ebde-486a-bc68-6b8eff290a19@sso-server/realms/63781 [07/Sep/2023:18:30:25 +0000] "GET /v3/auth/OS-FEDERATION/identity_providers/63781/protocols/openid/websso?origin=https://horizon-dashboard/auth/websso/ HTTP/1.1" 401 109
```

However, after running the Openstack  CLI command `openstack user list --domain DOMAIN` for the domain, the user is able to log in successfully.

Additionally, after a user has successfully signed in, after a period of brief inactivity (5-15 minutes), errors start appearing for the user that indicate Keystone can no longer find the user.  The errors that appear in the Keystone logs are below, and similar to the errors above.

```sh
[Thu Sep 07 18:32:27.934484 2023] [wsgi:error] [pid 5:tid 140298924193344] [remote XXX.XX.X.XXX:51772] 2023-09-07 18:32:27.934 5 WARNING keystone.server.flask.request_processing.middleware.auth_context [None req-4d101525-6d9c-49c5-9c09-ad5761226eb5 - - - - - -] Could not find user: 2fddeed8d53848cd89071eb41d1238c9.: keystone.exception.UserNotFound: Could not find user: 2fddeed8d53848cd89071eb41d1238c9.\x1b[00m
XXX.XX.X.XXX - - [07/Sep/2023:18:32:27 +0000] "GET /v3/users/2fddeed8-d538-48cd-8907-1eb41d1238c9/projects HTTP/1.1" 404 11
```

The user can log out, log back in successfully.

**Comment by etimmons-sp** [comment]
As a followup, I can confirm that after being signed in for too long, Horizon does a proper log out and redirects back to Horizon login screen.  So, somewhere between login and session timeout, the user goes into the state of not being able to be found.

**Comment by mnaser** [comment]
@robincron @mpiscaer i think this is similar to the issue that you might be seeing, so I think we might have to do some further checking, but seems to reflect the similar issue you're seeing.

**Comment by mnaser** [comment]
Solved by all the referenced PRs
