### ISSUE TITLE
The follow services are not running in the control plane

### ISSUE THREAD

**Issue by mpiscaer** [vexxhost/atmosphere#657]
ingress-nginx-defaultbackend-5c44d84866-5hf42
coredns-788c76bc67-4sd6m
coredns-788c76bc67-bvgjf
loki-gateway-789b47cbd5-pjc6n

**Comment by mpiscaer** [comment]
I was able to fix the loki-gateway with PR #658

But I don't know what ingress-nginx-defaultbackend does and where to find the config of coredns.

This coredns is not the neutron-coredns.

**Comment by mnaser** [comment]
For the ingress default backend:

https://github.com/vexxhost/atmosphere/blob/main/charts/ingress-nginx/values.yaml#L822-L826

**Comment by mnaser** [comment]
For the CoreDNS issue:

https://github.com/vexxhost/ansible-collection-kubernetes/issues/64

**Comment by mpiscaer** [comment]
> For the CoreDNS issue:
> 
> [vexxhost/ansible-collection-kubernetes#64](https://github.com/vexxhost/ansible-collection-kubernetes/issues/64)

Created https://github.com/vexxhost/ansible-collection-kubernetes/pull/65 to get this fixed
