### ISSUE TITLE
Remove fluxcd stuff finally

### ISSUE THREAD

**Issue by adeebx1** [vexxhost/atmosphere#691]
I got the following issue when trying to run atmosphere playbook with `kube-prometheus-stack` tag after configuring `kube_prometheus_stack_helm_values`

```
TASK [vexxhost.atmosphere.kube_prometheus_stack : Suspend the existing HelmRelease] *******************************************************************************************************************************
FAILED! => {"changed": false, "msg": "Failed to find exact match for helm.toolkit.fluxcd.io/v2beta1.HelmRelease by [kind, name, singularName, shortNames]"}
```

Note: I'm using `vexxhost.atmosphere 1.0.0-rc.1` collection

**Comment by adeebx1** [comment]
Sure we would like to upgrade our old version of the offline deployment, any recommendations to do so?

**Comment by mnaser** [comment]
@okozachenko1203 I am thinking that in Atmosphere 2.0 code, we remove all of this :)
