### ISSUE TITLE
Migrate to `cephadm`

### ISSUE THREAD

**Issue by mnaser** [vexxhost/atmosphere#711]
One of the challenges that we are starting to run into is the following:

- Ceph seems to be moving more and more away from packaging (some of the most newer releases support a very specific set of distribution packages)
- Using packages ties us into a very specific set of operating systems and makes it harder to upgrade operating systems because it's tied to Ceph
- Maintaining a whole code base that is focused around deploying, upgrading and operating Ceph starts to become overkill

We should be focused around minimizing the maintenance effort that we have & part of that is moving to `cephadm` to simply move to letting Ceph orchestrate itself.  This doesn't mean that the Ceph collection is not used anymore, since we still need 'something' to tell Ceph what to do.

Therefore, I think we should have the following steps

- [x] Create a new collection `vexxhost.containers`
- [x] Migrate `vexxhost.kubernetes.containerd` (and it's dependencies) to `vexxhost.containers`
- [x] Create a role called `vexxhost.containers.docker` which installs Docker from binaries (with `containerd` as a dependent role)

At this point, we've refactored `vexxhost.kubernetes` to depend on `vexxhost.containers` and now our `vexxhost.containers` role can also install Docker from binaries like the others

- [x] Update `vexxhost.ceph` to deploy using `cephadm` by default (handling SSH keys, etc)
- [x] Ensure `vexxhost.ceph` automatically adopts an existing legacy cluster if it finds one

At this point, the `vexxhost.ceph` collection is ready to roll.  It should then be as simple as a updating the dependency version inside Atmosphere and it'll automatically handle everything moving forward.  At that point, we should release with `pacific` but slowly and surely add follow-up releases which will upgrade clusters via `cephadm`.

**Comment by fitbeard** [comment]
And this is a good starting docker config for Atmosphere's need without bridges, iptables and with EL9 compatibility:
```
docker_daemon_options:
  bridge: "none"
  ip-forward: false
  iptables: false
  live-restore: true
  log-opts:
    max-file: "5"
    max-size: "50m"
  default-ulimits:
    nofile:
      name: "nofile"
      soft: 1048576
      hard: 1048576
```

```
cat /etc/docker/daemon.json
{
    "bridge": "none",
    "default-ulimits": {
        "nofile": {
            "hard": 1048576,
            "name": "nofile",
            "soft": 1048576
        }
    },
    "ip-forward": false,
    "iptables": false,
    "live-restore": true,
    "log-opts": {
        "max-file": "5",
        "max-size": "50m"
    }
}
```
