### ISSUE TITLE
fr: DPDK support in OVN

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/atmosphere#724]
Compute nodes configured with OVS DPDK should set the datapath_type as `netdev` for the integration bridge (managed by OVN) and all other bridges if connected to the integration bridge via patch ports. The below command can be used to set the datapath_type.
```
$ sudo ovs-vsctl set Bridge br-int datapath_type=netdev
```

**Comment by thywyn** [comment]
please see **https://github.com/vexxhost/atmosphere/pull/767**

**Comment by thywyn** [comment]
please see PR https://github.com/vexxhost/atmosphere/pull/769/files

**Comment by mnaser** [comment]
@thywyn thanks for the commits!  I think this means we've covered most of the outstanding issues, i think one last nice to have is documentation about setting it up.

Is it possible to share your current neutron/ovs/ovn vars to use as an example?

**Comment by thywyn** [comment]
Not quite all.  Please see this PR for the last piece:

[PR 773](https://github.com/vexxhost/atmosphere/pull/773)

It's lazy but it worked.. :)

**Comment by thywyn** [comment]
Documentation update is PR #774

**Comment by mnaser** [comment]
landed all but PR #773 -- we just need to get the OVN test to pass and I think it failed for unrelated reasons.
