### ISSUE TITLE
Nova pods stuck due to VIR_CONNECT_LIST_NODE_DEVICES_CAP_VDPA

### ISSUE THREAD

**Issue by guilhermesteinmuller** [vexxhost/atmosphere#741]
We have been seeing these tracebacks on nova pods across different atmosphere deployments:

```
ERROR nova.compute.manager AttributeError: module 'libvirt' has no attribute 'VIR_CONNECT_LIST_NODE_DEVICES_CAP_VDPA'
```

Which leads computes be stuck and not processing any requests. It is necessary to restart the pod in order to make the requests to flow again. 

refer also to https://bugs.launchpad.net/devstack/+bug/1933096

The environments are running libvirt 8.0.0

**Comment by mnaser** [comment]
I believe the root cause of this is that we were installing libvirt using PyPI instead of the distro packages.  I moved to using `python3-libvirt` which should get us a version that was built on the same platform.
