### ISSUE TITLE
Allow for missing trusts for Magnum cluster deletion

### ISSUE THREAD

**Issue by mnaser** [vexxhost/atmosphere#8]
In the referenced issue, we are failing to delete a cluster because the trust is already gone, we should handle that exception and just pass through if it's already gone instead of failing because we can't delete something that already doesn't exist.

**Comment by ricolin** [comment]
okay stable branch merged https://review.opendev.org/c/openstack/magnum/+/854136
thanks @mnaser

**Comment by ricolin** [comment]
I guess we can close this now.

**Comment by mnaser** [comment]
@ricolin indeed, this can be closed, but also with magnum-cluster-api, we're leveraging appcreds instead which should be much neater.
