### ISSUE TITLE
python-memcached 1.61 causes errors in Horizon

### ISSUE THREAD

**Issue by etimmons** [vexxhost/atmosphere#861]
_deletetouch() has been removed from python-memcached as of 1.60 and is causing errors in horizon

```
AttributeError: 'Client' object has no attribute '_deletetouch'
```

see https://github.com/django/django/pull/17648

as noted in the link above, this only affects django 3.2

**Comment by etimmons** [comment]
also: https://stackoverflow.com/a/77757428

**Comment by mnaser** [comment]
fixed, thanks @etimmons
