### ISSUE TITLE
Update doc

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/atmosphere#88]
I found that atmosphere includes `atmosphere` k8s operator as a role and introduced poetry as dependency manager.
Also in molecule, it uses `docker` and `ttl.sh` for atmosphere operator image build.
Those new changes require pre-requisites for end users. It should be reflected documentation.

**Comment by okozachenko1203** [comment]
- python 3.10
- poetry
- docker

**Comment by mnaser** [comment]
I think we should totally wrap this up by using Poetry only which is what I am aiming to do at the moment.

**Comment by mnaser** [comment]
this is already done
