### ISSUE TITLE
Octavia fails to create new load balancers

### ISSUE THREAD

**Issue by mnaser** [vexxhost/atmosphere#893]
https://bugs.launchpad.net/octavia/+bug/2049551

**Comment by ricolin** [comment]
track patch: https://review.opendev.org/c/openstack/octavia/+/905794

**Comment by mnaser** [comment]
We have a downstream patch for this so we can close this in Atmosphere, we can keep tracking the upstream bug moving forward and hopefully eliminate all the patches we have in the `images` folder.  Thanks @ricolin !

https://github.com/vexxhost/atmosphere/commit/fcc1a6d22e9dd3b4228b900fbd5857eaecac2527

**Comment by ricolin** [comment]
once https://review.opendev.org/c/openstack/octavia/+/912062 merged, we can remove patch from images/octavia/patches/octavia
