### ISSUE TITLE
Horizon 2023.2: requests to /api/lbaas/loadbalancers/?full=true endpoint from Network > Load Balancers panel results in 404 errors.

### ISSUE THREAD

**Issue by etimmons** [vexxhost/atmosphere#898]
After updating the newest, hardened build of Horizon 2023.2, we started experiencing errors on the Network > Load Balancers page in Horizon.

We rolled back to the previous Horizon 2023.2 build (still hosted in quay.io) and the endpoint began working again.

Endpoint:
https://HORIZON/api/lbaas/loadbalancers/?full=true

called from:
https://HORIZON/project/load_balancer/

**Comment by mnaser** [comment]
Hey @etimmons !

Can you please try the following image: 

```
ghcr.io/vexxhost/atmosphere/horizon:2023.2@sha256:e13a1ddb5326ec298d5bd0577db59543b11b0e1e76da5b3eb54e09c6e00f7209
```

We had to roll back some things, we'll have to manually maintain these.

**Comment by mnaser** [comment]
Just wanted to follow-up and circle back on this, got a new image that has no issues at all:

```
ghcr.io/vexxhost/atmosphere/horizon:2023.2@sha256:c1b0d1b55a1f0286445e6676123cf02e315bf362578d1169615630908b4d7851
```

We're rolling out the same fixes across all images to clear them out of all CVEs, but you should be good to go for now :)
