### ISSUE TITLE
Run keycloak related tasks on remote servers instead of local delegation

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/atmosphere#955]
We run `community.general.keycloak_*` tasks on deployment server(delegating localhost) to create keycloak resources like realm and clients.
In some customers' env, auth endpoint is not reachable from the deployment server because of their policy or compliance.
There is no specific reason to run them on localhost.

**Comment by okozachenko1203** [comment]
this could be a challenge https://github.com/vexxhost/atmosphere/blob/main/roles/keystone/templates/configmap-openid-metadata.yml.j2#L12

**Comment by mnaser** [comment]
delegates removed!
