### ISSUE TITLE
1.10.4 magnum image doesn't include helm cli

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/atmosphere#996]
The last zed image which includes helm is `quay.io/vexxhost/magnum-cluster-api:zed@sha256:6bfe28acf3648a2415658f2ea1e82ad5e08f66bc3620abd592e70e6aaebc0f73`.

**Comment by okozachenko1203** [comment]
@mnaser  we only build one release images in the project so no way to update clouds with older releases like zed.
1.10.4 uses zed magnum images but that image doesn't include helm so we cannot use that. We don't build zed images anymore so i had to use the old image which has older version of mcapi that the version mentioned in the release notes.

**Comment by mnaser** [comment]
I think this is cleared out by #1068
